'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import { ArrowLeft, Clock, BookOpen, Share2 } from 'lucide-react'
import { notFound } from 'next/navigation'

type Story = {
  title: string
  author: string
  year: string
  theme: string
  readTime: string
  dropCap: string
  content: string[]
  pullQuote?: string
}

const storyData: Record<string, Story> = {
  'shooting-an-elephant': {
    title: 'Shooting an Elephant',
    author: 'George Orwell',
    year: '1936',
    theme: 'Imperialism & Conscience',
    readTime: '12 min',
    dropCap: 'I',
    pullQuote: "I perceived in this moment that when the white man turns tyrant it is his own freedom that he destroys.",
    content: [
      "n Moulmein, in Lower Burma, I was hated by large numbers of people–the only time in my life that I have been important enough for this to happen to me. I was sub-divisional police officer of the town, and in an aimless, petty kind of way anti-European feeling was very bitter. No one had the guts to raise a riot, but if a European woman went through the bazaars alone somebody would probably spit betel juice over her dress. As a police officer I was an obvious target and was baited whenever it seemed safe to do so. When a nimble Burman tripped me up on the football field and the referee (another Burman) looked the other way, the crowd yelled with hideous laughter. This happened more than once. In the end the sneering yellow faces of young men that met me everywhere, the insults hooted after me when I was at a safe distance, got badly on my nerves. The young Buddhist priests were the worst of all. There were several thousands of them in the town and none of them seemed to have anything to do except stand on street corners and jeer at Europeans.",
      "All this was perplexing and upsetting. For at that time I had already made up my mind that imperialism was an evil thing and the sooner I chucked up my job and got out of it the better. Theoretically–and secretly, of course–I was all for the Burmese and all against their oppressors, the British. As for the job I was doing, I hated it more bitterly than I can perhaps make clear. In a job like that you see the dirty work of Empire at close quarters. The wretched prisoners huddling in the stinking cages of the lock-ups, the grey, cowed faces of the long-term convicts, the scarred buttocks of the men who had been Bogged with bamboos–all these oppressed me with an intolerable sense of guilt. But I could get nothing into perspective. I was young and ill-educated and I had had to think out my problems in the utter silence that is imposed on every Englishman in the East. I did not even know that the British Empire is dying, still less did I know that it is a great deal better than the younger empires that are going to supplant it. All I knew was that I was stuck between my hatred of the empire I served and my rage against the evil-spirited little beasts who tried to make my job impossible. With one part of my mind I thought of the British Raj as an unbreakable tyranny, as something clamped down, in saecula saeculorum, upon the will of prostrate peoples; with another part I thought that the greatest joy in the world would be to drive a bayonet into a Buddhist priest’s guts. Feelings like these are the normal by-products of imperialism; ask any Anglo-Indian official, if you can catch him off duty.",
      "One day something happened which in a roundabout way was enlightening. It was a tiny incident in itself, but it gave me a better glimpse than I had had before of the real nature of imperialism–the real motives for which despotic governments act. Early one morning the sub-inspector at a police station the other end of the town rang me up on the phone and said that an elephant was ravaging the bazaar. Would I please come and do something about it? I did not know what I could do, but I wanted to see what was happening and I got on to a pony and started out. I took my rifle, an old .44 Winchester and much too small to kill an elephant, but I thought the noise might be useful in terrorem. Various Burmans stopped me on the way and told me about the elephant’s doings. It was not, of course, a wild elephant, but a tame one which had gone \"must.\" It had been chained up, as tame elephants always are when their attack of \"must\" is due, but on the previous night it had broken its chain and escaped. Its mahout, the only person who could manage it when it was in that state, had set out in pursuit, but had taken the wrong direction and was now twelve hours’ journey away, and in the morning the elephant had suddenly reappeared in the town. The Burmese population had no weapons and were quite helpless against it. It had already destroyed somebody’s bamboo hut, killed a cow and raided some fruit-stalls and devoured the stock; also it had met the municipal rubbish van and, when the driver jumped out and took to his heels, had turned the van over and inflicted violences upon it.",
      "The Burmese sub-inspector and some Indian constables were waiting for me in the quarter where the elephant had been seen. It was a very poor quarter, a labyrinth of squalid bamboo huts, thatched with palmleaf, winding all over a steep hillside. I remember that it was a cloudy, stuffy morning at the beginning of the rains. We began questioning the people as to where the elephant had gone and, as usual, failed to get any definite information. That is invariably the case in the East; a story always sounds clear enough at a distance, but the nearer you get to the scene of events the vaguer it becomes. Some of the people said that the elephant had gone in one direction, some said that he had gone in another, some professed not even to have heard of any elephant. I had almost made up my mind that the whole story was a pack of lies, when we heard yells a little distance away. There was a loud, scandalized cry of \"Go away, child! Go away this instant!\" and an old woman with a switch in her hand came round the corner of a hut, violently shooing away a crowd of naked children. Some more women followed, clicking their tongues and exclaiming; evidently there was something that the children ought not to have seen. I rounded the hut and saw a man’s dead body sprawling in the mud. He was an Indian, a black Dravidian coolie, almost naked, and he could not have been dead many minutes. The people said that the elephant had come suddenly upon him round the corner of the hut, caught him with its trunk, put its foot on his back and ground him into the earth. This was the rainy season and the ground was soft, and his face had scored a trench a foot deep and a couple of yards long. He was lying on his belly with arms crucified and head sharply twisted to one side. His face was coated with mud, the eyes wide open, the teeth bared and grinning with an expression of unendurable agony. (Never tell me, by the way, that the dead look peaceful. Most of the corpses I have seen looked devilish.) The friction of the great beast’s foot had stripped the skin from his back as neatly as one skins a rabbit. As soon as I saw the dead man I sent an orderly to a friend’s house nearby to borrow an elephant rifle. I had already sent back the pony, not wanting it to go mad with fright and throw me if it smelt the elephant.",
      "The orderly came back in a few minutes with a rifle and five cartridges, and meanwhile some Burmans had arrived and told us that the elephant was in the paddy fields below, only a few hundred yards away. As I started forward practically the whole population of the quarter flocked out of the houses and followed me. They had seen the rifle and were all shouting excitedly that I was going to shoot the elephant. They had not shown much interest in the elephant when he was merely ravaging their homes, but it was different now that he was going to be shot. It was a bit of fun to them, as it would be to an English crowd; besides they wanted the meat. It made me vaguely uneasy. I had no intention of shooting the elephant–I had merely sent for the rifle to defend myself if necessary–and it is always unnerving to have a crowd following you. I marched down the hill, looking and feeling a fool, with the rifle over my shoulder and an ever-growing army of people jostling at my heels. At the bottom, when you got away from the huts, there was a metalled road and beyond that a miry waste of paddy fields a thousand yards across, not yet ploughed but soggy from the first rains and dotted with coarse grass. The elephant was standing eight yards from the road, his left side towards us. He took not the slightest notice of the crowd’s approach. He was tearing up bunches of grass, beating them against his knees to clean them and stuffing them into his mouth.",
      "I had halted on the road. As soon as I saw the elephant I knew with perfect certainty that I ought not to shoot him. It is a serious matter to shoot a working elephant–it is comparable to destroying a huge and costly piece of machinery–and obviously one ought not to do it if it can possibly be avoided. And at that distance, peacefully eating, the elephant looked no more dangerous than a cow. I thought then and I think now that his attack of \"must\" was already passing off; in which case he would merely wander harmlessly about until the mahout came back and caught him. Moreover, I did not in the least want to shoot him. I decided that I would watch him for a little while to make sure that he did not turn savage again, and then go home.",
      "But at that moment I glanced round at the crowd that had followed me. It was an immense crowd, two thousand at the least and growing every minute. It blocked the road for a long distance on either side. I looked at the sea of yellow faces above the garish clothes-faces all happy and excited over this bit of fun, all certain that the elephant was going to be shot. They were watching me as they would watch a conjurer about to perform a trick. They did not like me, but with the magical rifle in my hands I was momentarily worth watching. And suddenly I realized that I should have to shoot the elephant after all. The people expected it of me and I had got to do it; I could feel their two thousand wills pressing me forward, irresistibly. And it was at this moment, as I stood there with the rifle in my hands, that I first grasped the hollowness, the futility of the white man’s dominion in the East. Here was I, the white man with his gun, standing in front of the unarmed native crowd–seemingly the leading actor of the piece; but in reality I was only an absurd puppet pushed to and fro by the will of those yellow faces behind. I perceived in this moment that when the white man turns tyrant it is his own freedom that he destroys. He becomes a sort of hollow, posing dummy, the conventionalized figure of a sahib. For it is the condition of his rule that he shall spend his life in trying to impress the \"natives,\" and so in every crisis he has got to do what the \"natives\" expect of him. He wears a mask, and his face grows to fit it. I had got to shoot the elephant. I had committed myself to doing it when I sent for the rifle. A sahib has got to act like a sahib; he has got to appear resolute, to know his own mind and do definite things. To come all that way, rifle in hand, with two thousand people marching at my heels, and then to trail feebly away, having done nothing–no, that was impossible. The crowd would laugh at me. And my whole life, every white man’s life in the East, was one long struggle not to be laughed at.",
      "But I did not want to shoot the elephant. I watched him beating his bunch of grass against his knees, with that preoccupied grandmotherly air that elephants have. It seemed to me that it would be murder to shoot him. At that age I was not squeamish about killing animals, but I had never shot an elephant and never wanted to. (Somehow it always seems worse to kill a large animal.) Besides, there was the beast’s owner to be considered. Alive, the elephant was worth at least a hundred pounds; dead, he would only be worth the value of his tusks, five pounds, possibly. But I had got to act quickly. I turned to some experienced-looking Burmans who had been there when we arrived, and asked them how the elephant had been behaving. They all said the same thing: he took no notice of you if you left him alone, but he might charge if you went too close to him.",
      "It was perfectly clear to me what I ought to do. I ought to walk up to within, say, twenty-five yards of the elephant and test his behavior. If he charged, I could shoot; if he took no notice of me, it would be safe to leave him until the mahout came back. But also I knew that I was going to do no such thing. I was a poor shot with a rifle and the ground was soft mud into which one would sink at every step. If the elephant charged and I missed him, I should have about as much chance as a toad under a steam-roller. But even then I was not thinking particularly of my own skin, only of the watchful yellow faces behind. For at that moment, with the crowd watching me, I was not afraid in the ordinary sense, as I would have been if I had been alone. A white man mustn’t be frightened in front of \"natives\"; and so, in general, he isn’t frightened. The sole thought in my mind was that if anything went wrong those two thousand Burmans would see me pursued, caught, trampled on and reduced to a grinning corpse like that Indian up the hill. And if that happened it was quite probable that some of them would laugh. That would never do.",
      "There was only one alternative. I shoved the cartridges into the magazine and lay down on the road to get a better aim. The crowd grew very still, and a deep, low, happy sigh, as of people who see the theatre curtain go up at last, breathed from innumerable throats. They were going to have their bit of fun after all. The rifle was a beautiful German thing with cross-hair sights. I did not then know that in shooting an elephant one would shoot to cut an imaginary bar running from ear-hole to ear-hole. I ought, therefore, as the elephant was sideways on, to have aimed straight at his ear-hole, actually I aimed several inches in front of this, thinking the brain would be further forward.",
      "When I pulled the trigger I did not hear the bang or feel the kick–one never does when a shot goes home–but I heard the devilish roar of glee that went up from the crowd. In that instant, in too short a time, one would have thought, even for the bullet to get there, a mysterious, terrible change had come over the elephant. He neither stirred nor fell, but every line of his body had altered. He looked suddenly stricken, shrunken, immensely old, as though the frightful impact of the bullet had paralysed him without knocking him down. At last, after what seemed a long time–it might have been five seconds, I dare say–he sagged flabbily to his knees. His mouth slobbered. An enormous senility seemed to have settled upon him. One could have imagined him thousands of years old. I fired again into the same spot. At the second shot he did not collapse but climbed with desperate slowness to his feet and stood weakly upright, with legs sagging and head drooping. I fired a third time. That was the shot that did for him. You could see the agony of it jolt his whole body and knock the last remnant of strength from his legs. But in falling he seemed for a moment to rise, for as his hind legs collapsed beneath him he seemed to tower upward like a huge rock toppling, his trunk reaching skyward like a tree. He trumpeted, for the first and only time. And then down he came, his belly towards me, with a crash that seemed to shake the ground even where I lay.",
      "I got up. The Burmans were already racing past me across the mud. It was obvious that the elephant would never rise again, but he was not dead. He was breathing very rhythmically with long rattling gasps, his great mound of a side painfully rising and falling. His mouth was wide open–I could see far down into caverns of pale pink throat. I waited a long time for him to die, but his breathing did not weaken. Finally I fired my two remaining shots into the spot where I thought his heart must be. The thick blood welled out of him like red velvet, but still he did not die. His body did not even jerk when the shots hit him, the tortured breathing continued without a pause. He was dying, very slowly and in great agony, but in some world remote from me where not even a bullet could damage him further. I felt that I had got to put an end to that dreadful noise. It seemed dreadful to see the great beast lying there, powerless to move and yet powerless to die, and not even to be able to finish him. I sent back for my small rifle and poured shot after shot into his heart and down his throat. They seemed to make no impression. The tortured gasps continued as steadily as the ticking of a clock.",
      "In the end I could not stand it any longer and went away. I heard later that it took him half an hour to die. Burmans were bringing dahs and baskets even before I left, and I was told they had stripped his body almost to the bones by the afternoon.",
      "Afterwards, of course, there were endless discussions about the shooting of the elephant. The owner was furious, but he was only an Indian and could do nothing. Besides, legally I had done the right thing, for a mad elephant has to be killed, like a mad dog, if its owner fails to control it. Among the Europeans opinion was divided. The older men said I was right, the younger men said it was a damn shame to shoot an elephant for killing a coolie, because an elephant was worth more than any damn Coringhee coolie. And afterwards I was very glad that the coolie had been killed; it put me legally in the right and it gave me a sufficient pretext for shooting the elephant. I often wondered whether any of the others grasped that I had done it solely to avoid looking a fool."
    ]
  },
  'clean-well-lighted-place': {
    title: 'A Clean, Well-Lighted Place',
    author: 'Ernest Hemingway',
    year: '1933',
    theme: 'Nihilism & Solace',
    readTime: '6 min',
    dropCap: 'I',
    pullQuote: "It was a nothing that he knew too well. It was all a nothing and a man was a nothing too.",
    content: [
      "It was very late and everyone had left the café except an old man who sat in the shadow the leaves of the tree made against the electric light. In the day time the street was dusty, but at night the dew settled the dust and the old man liked to sit late because he was deaf and now at night it was quiet and he felt the difference. The two waiters inside the café knew that the old man was a little drunk, and while he was a good client they knew that if he became too drunk he would leave without paying, so they kept watch on him.",
      "\"Last week he tried to commit suicide,\" one waiter said.",
      "\"Why?\"",
      "\"He was in despair.\"",
      "\"What about?\"",
      "\"Nothing.\"",
      "\"How do you know it was nothing?\"",
      "\"He has plenty of money.\"",
      "They sat together at a table that was close against the wall near the door of the café and looked at the terrace where the tables were all empty except where the old man sat in the shadow of the leaves of the tree that moved slightly in the wind. A girl and a soldier went by in the street. The street light shone on the brass number on his collar. The girl wore no head covering and hurried beside him.",
      "\"The guard will pick him up,\" one waiter said.",
      "\"What does it matter if he gets what he's after?\"",
      "\"He had better get off the street now. The guard will get him. They went by five minutes ago.\"",
      "The old man sitting in the shadow rapped on his saucer with his glass. The younger waiter went over to him.",
      "\"What do you want?\"",
      "The old man looked at him. \"Another brandy,\" he said.",
      "\"You'll be drunk,\" the waiter said. The old man looked at him. The waiter went away.",
      "\"He'll stay all night,\" he said to his colleague. \"I'm sleepy now. I never get into bed before three o'clock. He should have killed himself last week.\"",
      "The waiter took the brandy bottle and another saucer from the counter inside the café and marched out to the old man's table. He put down the saucer and poured the glass full of brandy.",
      "\"You should have killed yourself last week,\" he said to the deaf man. The old man motioned with his finger. \"A little more,\" he said. The waiter poured on into the glass so that the brandy slopped over and ran down the stem into the top saucer of the pile. \"Thank you,\" the old man said. The waiter took the bottle back inside the café. He sat down at the table with his colleague again.",
      "\"He's drunk now,\" he said.",
      "\"He's drunk every night.\"",
      "\"What did he want to kill himself for?\"",
      "\"How should I know.\"",
      "\"How did he do it?\"",
      "\"He hung himself with a rope.\"",
      "\"Who cut him down?\"",
      "\"His niece.\"",
      "\"Why did they do it?\"",
      "\"Fear for his soul.\"",
      "\"How much money has he got?\"",
      "\"He's got plenty.\"",
      "\"He must be eighty years old.\"",
      "\"Anyway I should say he was eighty.\"",
      "\"I wish he would go home. I never get to bed before three o'clock. What kind of hour is that to go to bed?\"",
      "\"He stays up because he likes it.\"",
      "\"He's lonely. I'm not lonely. I have a wife waiting in bed for me.\"",
      "\"He had a wife once too.\"",
      "\"A wife would be no good to him now.\"",
      "\"You can't tell. He might be better with a wife.\"",
      "\"His niece looks after him.\"",
      "\"I know. You said she cut him down.\"",
      "\"I wouldn't want to be that old. An old man is a nasty thing.\"",
      "\"Not always. This old man is clean. He drinks without spilling. Even now, drunk. Look at him.\"",
      "\"I don't want to look at him. I wish he would go home. He has no regard for those who must work.\"",
      "The old man looked from his glass across the square, then over at the waiters.",
      "\"Another brandy,\" he said, pointing to his glass. The waiter who was in a hurry came over.",
      "\"Finished,\" he said, speaking with that omission of syntax stupid people employ when talking to drunken people or foreigners. \"No more tonight. Close now.\"",
      "\"Another,\" said the old man.",
      "\"No. Finished.\" The waiter wiped the edge of the table with a towel and shook his head.",
      "The old man stood up, slowly counted the saucers, took a leather coin purse from his pocket and paid for the drinks, leaving half a peseta tip.",
      "The waiter watched him go down the street, a very old man walking unsteadily but with dignity.",
      "\"Why didn't you let him stay and drink?\" the unhurried waiter asked. They were putting up the shutters. \"It is not half-past two.\"",
      "\"I want to go home to bed.\"",
      "\"What is an hour?\"",
      "\"More to me than to him.\"",
      "\"An hour is the same.\"",
      "\"You talk like an old man yourself. He can buy a bottle and drink at home.\"",
      "\"It's not the same.\"",
      "\"No, it is not,\" agreed the waiter with a wife. He did not wish to be unjust. He was only in a hurry.",
      "\"And you? You have no fear of going home before your usual hour?\"",
      "\"Are you trying to insult me?\"",
      "\"No, hombre, only to make a joke.\"",
      "\"No,\" the waiter who was in a hurry said, rising from pulling down the metal shutters. \"I have confidence. I am all confidence.\"",
      "\"You have youth, confidence, and a job,\" the older waiter said. \"You have everything.\"",
      "\"And what do you lack?\"",
      "\"Everything but work.\"",
      "\"You have everything I have.\"",
      "\"No. I have never had confidence and I am not young.\"",
      "\"Come on. Stop talking nonsense and lock up.\"",
      "\"I am of those who like to stay late at the cafe,\" the older waiter said. \"With all those who do not want to go to bed. With all those who need a light for the night.\"",
      "\"I want to go home and into bed.\"",
      "\"We are of two different kinds,\" the older waiter said. He was not dressed to go home. \"It is not only a question of youth and confidence although those things are very beautiful. Each night I am reluctant to close up because there may be some one who needs the café.\"",
      "\"Hombre, there are bodegas open all night long.\"",
      "\"You do not understand. This is a clean and pleasant café. It is well lighted. The light is very good and also, now, there are shadows of the leaves.\"",
      "\"Good night,\" said the younger waiter.",
      "\"Good night,\" the other said. Turning off the electric light he continued the conversation with himself. It is the light of course but it is necessary that the place be clean and pleasant. You do not want music. Certainly you do not want music. Nor can you stand before a bar with dignity although that is all that is provided for these hours. What did he fear? It was not a fear or dread. It was a nothing that he knew too well. It was all a nothing and a man was a nothing too. It was only that and light was all it needed and a certain cleanness and order. Some lived in it and never felt it but he knew it all was nada y pues nada y nada y pues nada. Our nada who art in nada, nada be thy name thy kingdom nada thy will be nada in nada as it is in nada. Give us this nada our daily nada and nada us our nada as we nada our nadas and nada us not into nada but deliver us from nada; pues nada. Hail nothing full of nothing, nothing is with thee. He smiled and stood before a bar with a shining steam pressure coffee machine.",
      "\"What's yours?\" asked the barman.",
      "\"Nada.\"",
      "\"Otro loco mas,\" said the barman and turned away.",
      "\"A little cup,\" said the waiter.",
      "The barman poured it for him.",
      "\"The light is very bright and pleasant but the bar is unpolished,\" the waiter said.",
      "The barman looked at him but did not answer. It was too late at night for conversation.",
      "\"You want another copita?\" the barman asked.",
      "\"No, thank you,\" said the waiter and went out. He disliked bars and bodegas. A clean, well-lighted café was a very different thing. Now, without thinking further, he would go home to his room. He would lie in the bed and finally, with daylight, he would go to sleep. After all, he said to himself, it's probably only insomnia. Many must have it."
    ]
  },
  'esme': {
    title: 'Esme',
    author: 'Saki (H.H. Munro)',
    year: '1911',
    theme: 'Social Irony',
    readTime: '8 min',
    dropCap: 'S',
    pullQuote: "In spite of everything that proverbs may say, poverty keeps together more homes than it breaks up.",
    content: [
      "\"All hunting stories are the same,\" said Clovis; \"just as all Turf stories are the same, and all--\"",
      "\"My hunting story isn't a bit like any you've ever heard,\" said the Baroness. \"It happened quite a while ago, when I was about twenty-three. I wasn't living apart from my husband then; you see, neither of us could afford to make the other a separate allowance. In spite of everything that proverbs may say, poverty keeps together more homes than it breaks up. But we always hunted with different packs. All this has nothing to do with the story.\"",
      "\"We haven't arrived at the meet yet. I suppose there was a meet,\" said Clovis.",
      "\"Of course there was a meet,\" said the Baroness; \"all the usual crowd were there, especially Constance Broddle. Constance is one of those strapping florid girls that go so well with autumn scenery or Christmas decorations in church. 'I feel a presentiment that something dreadful is going to happen,' she said to me; 'am I looking pale?'\"",
      "\"She was looking about as pale as a beetroot that has suddenly heard bad news.\"",
      "\"'You're looking nicer than usual,' I said, 'but that's so easy for you.' Before she had got the right bearings of this remark we had settled down to business; hounds had found a fox lying out in some gorse-bushes.\"",
      "\"I knew it,\" said Clovis; \"in every fox-hunting story that I've ever heard there's been a fox and some gorse-bushes.\"",
      "\"Constance and I were well mounted,\" continued the Baroness serenely, \"and we had no difficulty in keeping ourselves in the first flight, though it was a fairly stiff run. Towards the finish, however, we must have held rather too independent a line, for we lost the hounds, and found ourselves plodding aimlessly along miles away from anywhere. It was fairly exasperating, and my temper was beginning to let itself go by inches, when on pushing our way through an accommodating hedge we were gladdened by the sight of hounds in full cry in a hollow just beneath us.\"",
      "\"'There they go,' cried Constance, and then added in a gasp, 'In Heaven's name, what are they hunting?'\"",
      "\"It was certainly no mortal fox. It stood more than twice as high, had a short, ugly head, and an enormous thick neck.\"",
      "\"'It's a hyena,' I cried; 'it must have escaped from Lord Pabham's Park.'\"",
      "\"At that moment the hunted beast turned and faced its pursuers, and the hounds (there were only about six couple of them) stood round in a half-circle and looked foolish. Evidently they had broken away from the rest of the pack on the trail of this alien scent, and were not quite sure how to treat their quarry now they had got him.\"",
      "\"The hyena hailed our approach with unmistakable relief and demonstrations of friendliness. It had probably been accustomed to uniform kindness from humans, while its first experience of a pack of hounds had left a bad impression. The hounds looked more than ever embarrassed as their quarry paraded its sudden intimacy with us, and the faint toot of a horn in the distance was seized on as a welcome signal for unobtrusive departure. Constance and I and the hyena were left alone in the gathering twilight.\"",
      "\"'What are we to do?' asked Constance.\"",
      "\"'What a person you are for questions,' I said.\"",
      "\"'Well, we can't stay here all night with a hyena,' she retorted.\"",
      "\"'I don't know what your ideas of comfort are,' I said; 'but I shouldn't think of staying here all night even without a hyena. My home may be an unhappy one, but at least it has hot and cold water laid on, and domestic service, and other conveniences which we shouldn't find here. We had better make for that ridge of trees to the right; I imagine the Crowley road is just beyond.'\"",
      "\"We trotted off slowly along a faintly marked cart-track, with the beast following cheerfully at our heels.\"",
      "\"'What on earth are we to do with the hyena?' came the inevitable question.\"",
      "\"'What does one generally do with hyenas?' I asked crossly.\"",
      "\"'I've never had anything to do with one before,' said Constance.\"",
      "\"'Well, neither have I. If we even knew its sex we might give it a name. Perhaps we might call it Esme. That would do in either case.\"",
      "\"There was still sufficient daylight for us to distinguish wayside objects, and our listless spirits gave an upward perk as we came upon a small half-naked gipsy brat picking blackberries from a low-growing bush. The sudden apparition of two horsewomen and a hyena set it off crying, and in any case we should scarcely have gleaned any useful geographical information from that source; but there was a probability that we might strike a gipsy encampment somewhere along our route. We rode on hopefully but uneventfully for another mile or so.\"",
      "\"'I wonder what the child was doing there,' said Constance presently.\"",
      "\"'Picking blackberries. Obviously.'\"",
      "\"'I don't like the way it cried,' pursued Constance; 'somehow its wail keeps ringing in my ears.'\"",
      "\"I did not chide Constance for her morbid fancies; as a matter of fact the same sensation, of being pursued by a persistent fretful wail, had been forcing itself on my rather over-tired nerves. For company's sake I hulloed to Esme, who had lagged somewhat behind. With a few springy bounds he drew up level, and then shot past us.\"",
      "\"The wailing accompaniment was explained. The gipsy child was firmly, and I expect painfully, held in his jaws.\"",
      "\"'Merciful Heaven!' screamed Constance, 'what on earth shall we do? What are we to do?'\"",
      "\"I am perfectly certain that at the Last Judgment Constance will ask more questions than any of the examining Seraphs.\"",
      "\"'Can't we do something?' she persisted tearfully, as Esme cantered easily along in front of our tired horses.\"",
      "\"Personally I was doing everything that occurred to me at the moment. I stormed and scolded and coaxed in English and French and gamekeeper language; I made absurd, ineffectual cuts in the air with my thongless hunting-crop; I hurled my sandwich case at the brute; in fact, I really don't know what more I could have done. And still we lumbered on through the deepening dusk, with that dark uncouth shape lumbering ahead of us, and a drone of lugubrious music floating in our ears. Suddenly Esme bounded aside into some thick bushes, where we could not follow; the wail rose to a shriek and then stopped altogether. This part of the story I always hurry over, because it is really rather horrible. When the beast joined us again, after an absence of a few minutes, there was an air of patient understanding about him, as though he knew that he had done something of which we disapproved, but which he felt to be thoroughly justifiable.\"",
      "\"'How can you let that ravening beast trot by your side?' asked Constance. She was looking more than ever like an albino beetroot.\"",
      "\"'In the first place, I can't prevent it,' I said; 'and in the second place, whatever else he may be, I doubt if he's ravening at the present moment.'\"",
      "\"Constance shuddered. 'Do you think the poor little thing suffered much?' came another of her futile questions.\"",
      "\"'The indications were all that way,' I said; 'on the other hand, of course, it may have been crying from sheer temper. Children sometimes do.'\"",
      "\"It was nearly pitch-dark when we emerged suddenly into the high road. A flash of lights and the whir of a motor went past us at the same moment at uncomfortably close quarters. A thud and a sharp screeching yell followed a second later. The car drew up, and when I had ridden back to the spot I found a young man bending over a dark motionless mass lying by the roadside.\"",
      "\"'You have killed my Esme,' I exclaimed bitterly.\"",
      "\"'I'm so awfully sorry,' said the young man; 'I keep dogs myself, so I know what you must feel about it. I'll do anything I can in reparation.'\"",
      "\"'Please bury him at once,' I said; 'that much I think I may ask of you.'\"",
      "\"'Bring the spade, William,' he called to the chauffeur. Evidently hasty roadside interments were contingencies that had been provided against.\"",
      "\"The digging of a sufficiently large grave took some little time. 'I say, what a magnificent fellow,' said the motorist as the corpse was rolled over into the trench. 'I'm afraid he must have been rather a valuable animal.'\"",
      "\"'He took second in the puppy class at Birmingham last year,' I said resolutely. Constance snorted loudly.\"",
      "\"'Don't cry, dear,' I said brokenly; 'it was all over in a moment. He couldn't have suffered much.'\"",
      "\"'Look here,' said the young fellow desperately, 'you simply must let me do something by way of reparation.'\"",
      "\"I refused sweetly, but as he persisted I let him have my address.\"",
      "\"Of course, we kept our own counsel as to the earlier episodes of the evening. Lord Pabham never advertised the loss of his hyena; when a strictly fruit-eating animal strayed from his park a year or two previously he was called upon to give compensation in eleven cases of sheep-worrying and practically to re-stock his neighbours' poultry-yards, and an escaped hyena would have mounted up to something on the scale of a Government grant. The gipsies were equally unobtrusive over their missing offspring; I don't suppose in large encampments they really know to a child or two how many they've got.\"",
      "The Baroness paused reflectively, and then continued:",
      "\"There was a sequel to the adventure, though. I got through the post a charming little diamond broach, with the name Esme set in a sprig of rosemary. Incidentally, too, I lost the friendship of Constance Broddle. You see, when I sold the brooch I quite properly refused to give her any share of the proceeds. I pointed out that the Esme part of the affair was my own invention, and the hyena part of it belonged to Lord Pabham, if it really was his hyena, of which,of course, I've no proof.\""
    ]
  },
  'the-black-cat': {
    title: 'The Black Cat',
    author: 'Edgar Allan Poe',
    year: '1843',
    theme: 'Guilt & Phantasm',
    readTime: '15 min',
    dropCap: 'F',
    pullQuote: "I blush, I burn, I shudder, while I pen the damnable atrocity.",
    content: [
      "FOR the most wild yet most homely narrative which I am about to pen, I neither expect nor solicit belief. Mad indeed would I be to expect it, in a case where my very senses reject their own evidence. Yet, mad am I not—and very surely do I not dream. But to-morrow I die, and to-day I would unburden my soul. My immediate purpose is to place before the world, plainly, succinctly, and without comment, a series of mere household events. In their consequences, these events have terrified—have tortured—have destroyed me. Yet I will not attempt to expound them. To me, they have presented little but horror—to many they will seem less terrible than baroques. Hereafter, perhaps, some intellect may be found which will reduce my phantasm to the commonplace—some intellect more calm, more logical, and far less excitable than my own, which will perceive, in the circumstances I detail with awe, nothing more than an ordinary succession of very natural causes and effects.",
      "From my infancy I was noted for the docility and humanity of my disposition. My tenderness of heart was even so conspicuous as to make me the jest of my companions. I was especially fond of animals, and was indulged by my parents with a great variety of pets. With these I spent most of my time, and never was so happy as when feeding and caressing them. This peculiarity of character grew with my growth, and, in my manhood, I derived from it one of my principal sources of pleasure. To those who have cherished an affection for a faithful and sagacious dog, I need hardly be at the trouble of explaining the nature or the intensity of the gratification thus derivable. There is something in the unselfish and self-sacrificing love of a brute, which goes directly to the heart of him who has had frequent occasion to test the paltry friendship and gossamer fidelity of mere Man.",
      "I married early, and was happy to find in my wife a disposition not uncongenial with my own. Observing my partiality for domestic pets, she lost no opportunity of procuring those of the most agreeable kind. We had birds, gold-fish, a fine dog, rabbits, a small monkey, and a cat. This latter was a remarkably large and beautiful animal, entirely black, and sagacious to an astonishing degree. In speaking of his intelligence, my wife, who at heart was not a little tinctured with superstition, made frequent allusion to the ancient popular notion, which regarded all black cats as witches in disguise. Not that she was ever serious upon this point—and I mention the matter at all for no better reason than that it happens, just now, to be remembered.",
      "Pluto—this was the cat’s name—was my favorite pet and playmate. I alone fed him, and he attended me wherever I went about the house. It was even with difficulty that I could prevent him from following me through the streets. Our friendship lasted, in this manner, for several years, during which my general temperament and character—through the instrumentality of the Fiend Intemperance—had (I blush to confess it) experienced a radical alteration for the worse. I grew, day by day, more moody, more irritable, more regardless of the feelings of others. I suffered myself to use intemperate language to my wife. At length, I even offered her personal violence. My pets, of course, were made to feel the change in my disposition. I not only neglected, but ill-used them. For Pluto, however, I still retained sufficient regard to restrain me from maltreating him, as I made no scruple of maltreating the rabbits, the monkey, or even the dog, when, by accident, or through affection, they came in my way. But my disease grew upon me—for what disease is like Alcohol!—and at length even Pluto, who was now becoming old, and consequently somewhat peevish—even Pluto began to experience the effects of my ill temper.",
      "One night, returning home, much intoxicated, from one of my haunts about town, I fancied that the cat avoided my presence. I seized him; when, in his fright at my violence, he inflicted a slight wound upon my hand with his teeth. The fury of a demon instantly possessed me. I knew myself no longer. My original soul seemed, at once, to take its flight from my body; and a more than fiendish malevolence, gin-nurtured, thrilled every fibre of my frame. I took from my waistcoat-pocket a penknife, opened it, grasped the poor beast by the throat, and deliberately cut one of its eyes from the socket! I blush, I burn, I shudder, while I pen the damnable atrocity.",
      "When reason returned with the morning—when I had slept off the fumes of the night’s debauch—I experienced a sentiment half of horror, half of remorse, for the crime of which I had been guilty; but it was, at best, a feeble and equivocal feeling, and the soul remained untouched. I again plunged into excess, and soon drowned in wine all memory of the deed.",
      "In the meantime the cat slowly recovered. The socket of the lost eye presented, it is true, a frightful appearance, but he no longer appeared to suffer any pain. He went about the house as usual, but, as might be expected, fled in extreme terror at my approach. I had so much of my old heart left, as to be at first grieved by this evident dislike on the part of a creature which had once so loved me. But this feeling soon gave place to irritation. And then came, as if to my final and irrevocable overthrow, the spirit of PERVERSENESS. Of this spirit philosophy takes no account. Yet I am not more sure that my soul lives, than I am that perverseness is one of the primitive impulses of the human heart—one of the indivisible primary faculties, or sentiments, which give direction to the character of Man. Who has not, a hundred times, found himself committing a vile or a stupid action, for no other reason than because he knows he should not? Have we not a perpetual inclination, in the teeth of our best judgment, to violate that which is Law, merely because we understand it to be such? This spirit of perverseness, I say, came to my final overthrow. It was this unfathomable longing of the soul to vex itself—to offer violence to its own nature—to do wrong for the wrong’s sake only—that urged me to continue and finally to consummate the injury I had inflicted upon the unoffending brute. One morning, in cold blood, I slipped a noose about its neck and hung it to the limb of a tree;—hung it with the tears streaming from my eyes, and with the bitterest remorse at my heart;—hung it because I knew that it had loved me, and because I felt it had given me no reason of offence;—hung it because I knew that in so doing I was committing a sin—a deadly sin that would so jeopardize my immortal soul as to place it—if such a thing were possible—even beyond the reach of the infinite mercy of the Most Merciful and Most Terrible God.",
      "On the night of the day on which this most cruel deed was done, I was aroused from sleep by the cry of fire. The curtains of my bed were in flames. The whole house was blazing. It was with great difficulty that my wife, a servant, and myself, made our escape from the conflagration. The destruction was complete. My entire worldly wealth was swallowed up, and I resigned myself thenceforward to despair.",
      "I am above the weakness of seeking to establish a sequence of cause and effect, between the disaster and the atrocity. But I am detailing a chain of facts—and wish not to leave even a possible link imperfect. On the day succeeding the fire, I visited the ruins. The walls, with one exception, had fallen in. This exception was found in a compartment wall, not very thick, which stood about the middle of the house, and against which had rested the head of my bed. The plastering had here, in great measure, resisted the action of the fire—a fact which I attributed to its having been recently spread. About this wall a dense crowd were collected, and many persons seemed to be examining a particular portion of it with very minute and eager attention. The words “strange!” “singular!” and other similar expressions, excited my curiosity. I approached and saw, as if graven in bas-relief upon the white surface, the figure of a gigantic cat. The impression was given with an accuracy truly marvellous. There was a rope about the animal’s neck.",
      "When I first beheld this apparition—for I could scarcely regard it as less—my wonder and my terror were extreme. But at length reflection came to my aid. The cat, I remembered, had been hung in a garden adjacent to the house. Upon the alarm of fire, this garden had been immediately filled by the crowd—by some one of whom the animal must have been cut from the tree and thrown, through an open window, into my chamber. This had probably been done with the view of arousing me from sleep. The falling of other walls had compressed the victim of my cruelty into the substance of the freshly-spread plaster; the lime of which, with the flames, and the ammonia from the carcass, had then accomplished the portraiture as I saw it.",
      "Although I thus readily accounted to my reason, if not altogether to my conscience, for the startling fact just detailed, it did not the less fail to make a deep impression upon my fancy. For months I could not rid myself of the phantasm of the cat; and, during this period, there came back into my spirit a half-sentiment that seemed, but was not, remorse. I went so far as to regret the loss of the animal, and to look about me, among the vile haunts which I now habitually frequented, for another pet of the same species, and of somewhat similar appearance, with which to supply its place.",
      "One night as I sat, half stupefied, in a den of more than infamy, my attention was suddenly drawn to some black object, reposing upon the head of one of the immense hogsheads of gin, or of rum, which constituted the chief furniture of the apartment. I had been looking steadily at the top of this hogshead for some minutes, and what now caused me surprise was the fact that I had not sooner perceived the object thereupon. I approached it, and touched it with my hand. It was a black cat—a very large one—fully as large as Pluto, and closely resembling him in every respect but one. Pluto had not a white hair upon any portion of his body; but this cat had a large, although indefinite splotch of white, covering nearly the whole region of the breast.",
      "Upon my touching him, he immediately arose, purred loudly, rubbed against my hand, and appeared delighted with my notice. This, then, was the very creature of which I was in search. I at once offered to purchase it of the landlord; but this person made no claim to it—knew nothing of it—had never seen it before.",
      "I continued my caresses, and, when I prepared to go home, the animal evinced a disposition to accompany me. I permitted it to do so; occasionally stooping and patting it as I proceeded. When it reached the house it domesticated itself at once, and became immediately a great favorite with my wife.",
      "For my own part, I soon found a dislike to it arising within me. This was just the reverse of what I had anticipated; but—I know not how or why it was—its evident fondness for myself rather disgusted and annoyed me. By slow degrees, these feelings of disgust and annoyance rose into the bitterness of hatred. I avoided the creature; a certain sense of shame, and the remembrance of my former deed of cruelty, preventing me from physically abusing it. I did not, for some weeks, strike, or otherwise violently ill use it; but gradually—very gradually—I came to look upon it with unutterable loathing, and to flee silently from its odious presence, as from the breath of a pestilence.",
      "What added, no doubt, to my hatred of the beast, was the discovery, on the morning after I brought it home, that, like Pluto, it also had been deprived of one of its eyes. This circumstance, however, only endeared it to my wife, who, as I have already said, possessed, in a high degree, that humanity of feeling which had once been my distinguishing trait, and the source of many of my simplest and purest pleasures.",
      "With my aversion to this cat, however, its partiality for myself seemed to increase. It followed my footsteps with a pertinacity which it would be difficult to make the reader comprehend. Whenever I sat, it would crouch beneath my chair, or spring upon my knees, covering me with its loathsome caresses. If I arose to walk it would get between my feet and thus nearly throw me down, or, fastening its long and sharp claws in my dress, clamber, in this manner, to my breast. At such times, although I longed to destroy it with a blow, I was yet withheld from so doing, partly by a memory of my former crime, but chiefly—let me confess it at once—by absolute dread of the beast.",
      "This dread was not exactly a dread of physical evil—and yet I should be at a loss how otherwise to define it. I am almost ashamed to own—yes, even in this felon’s cell, I am almost ashamed to own—that the terror and horror with which the animal inspired me, had been heightened by one of the merest chimeras it would be possible to conceive. My wife had called my attention, more than once, to the character of the mark of white hair, of which I have spoken, and which constituted the sole visible difference between the strange beast and the one I had destroyed. The reader will remember that this mark, although large, had been originally very indefinite; but, by slow degrees—degrees nearly imperceptible, and which for a long time my reason struggled to reject as fanciful—it had, at length, assumed a rigorous distinctness of outline. It was now the representation of an object that I shudder to name—and for this, above all, I loathed, and dreaded, and would have rid myself of the monster had I dared—it was now, I say, the image of a hideous—of a ghastly thing—of the GALLOWS!—oh, mournful and terrible engine of Horror and of Crime—of Agony and of Death!",
      "And now was I indeed wretched beyond the wretchedness of mere Humanity. And a brute beast—whose fellow I had contemptuously destroyed—a brute beast to work out for me—for me, a man fashioned in the image of the High God—so much of insufferable woe! Alas! neither by day nor by night knew I the blessing of rest any more! During the former the creature left me no moment alone, and in the latter I started hourly from dreams of unutterable fear to find the hot breath of the thing upon my face, and its vast weight—an incarnate nightmare that I had no power to shake off—incumbent eternally upon my heart!",
      "Beneath the pressure of torments such as these the feeble remnant of the good within me succumbed. Evil thoughts became my sole intimates—the darkest and most evil of thoughts. The moodiness of my usual temper increased to hatred of all things and of all mankind; while from the sudden, frequent, and ungovernable outbursts of a fury to which I now blindly abandoned myself, my uncomplaining wife, alas, was the most usual and the most patient of sufferers.",
      "One day she accompanied me, upon some household errand, into the cellar of the old building which our poverty compelled us to inhabit. The cat followed me down the steep stairs, and, nearly throwing me headlong, exasperated me to madness. Uplifting an axe, and forgetting, in my wrath, the childish dread which had hitherto stayed my hand, I aimed a blow at the animal, which, of course, would have proved instantly fatal had it descended as I wished. But this blow was arrested by the hand of my wife. Goaded by the interference into a rage more than demoniacal, I withdrew my arm from her grasp and buried the axe in her brain. She fell dead upon the spot without a groan.",
      "This hideous murder accomplished, I set myself forthwith, and with entire deliberation, to the task of concealing the body. I knew that I could not remove it from the house, either by day or by night, without the risk of being observed by the neighbors. Many projects entered my mind. At one period I thought of cutting the corpse into minute fragments, and destroying them by fire. At another, I resolved to dig a grave for it in the floor of the cellar. Again, I deliberated about casting it in the well in the yard—about packing it in a box, as if merchandise, with the usual arrangements, and so getting a porter to take it from the house. Finally I hit upon what I considered a far better expedient than either of these. I determined to wall it up in the cellar, as the monks of the Middle Ages are recorded to have walled up their victims.",
      "For a purpose such as this the cellar was well adapted. Its walls were loosely constructed, and had lately been plastered throughout with a rough plaster, which the dampness of the atmosphere had prevented from hardening. Moreover, in one of the walls was a projection, caused by a false chimney, or fireplace, that had been filled up and made to resemble the rest of the cellar. I made no doubt that I could readily displace the bricks at this point, insert the corpse, and wall the whole up as before, so that no eye could detect any thing suspicious.",
      "And in this calculation I was not deceived. By means of a crowbar I easily dislodged the bricks, and, having carefully deposited the body against the inner wall, I propped it in that position, while with little trouble, I re-laid the whole structure as it originally stood. Having procured mortar, sand, and hair, with every possible precaution, I prepared a plaster which could not be distinguished from the old, and with this I very carefully went over the new brickwork. When I had finished, I felt satisfied that all was right. The wall did not present the slightest appearance of having been disturbed. The rubbish on the floor was picked up with the minutest care. I looked around triumphantly, and said to myself: “Here at least, then, my labor has not been in vain.”",
      "My next step was to look for the beast which had been the cause of so much wretchedness; for I had, at length, firmly resolved to put it to death. Had I been able to meet with it at the moment, there could have been no doubt of its fate; but it appeared that the crafty animal had been alarmed at the violence of my previous anger, and forbore to present itself in my present mood. It is impossible to describe or to imagine the deep, the blissful sense of relief which the absence of the detested creature occasioned in my bosom. It did not make its appearance during the night; and thus for one night, at least, since its introduction into the house, I soundly and tranquilly slept; aye, slept even with the burden of murder upon my soul.",
      "The second and the third day passed, and still my tormentor came not. Once again I breathed as a free man. The monster, in terror, had fled the premises for ever! I should behold it no more! My happiness was supreme! The guilt of my dark deed disturbed me but little. Some few inquiries had been made, but these had been readily answered. Even a search had been instituted—but of course nothing was to be discovered. I looked upon my future felicity as secured.",
      "Upon the fourth day of the assassination, a party of the police came, very unexpectedly, into the house, and proceeded again to make rigorous investigation of the premises. Secure, however, in the inscrutability of my place of concealment, I felt no embarrassment whatever. The officers bade me accompany them in their search. They left no nook or corner unexplored. At length, for the third or fourth time, they descended into the cellar. I quivered not in a muscle. My heart beat calmly as that of one who slumbers in innocence. I walked the cellar from end to end. I folded my arms upon my bosom, and roamed easily to and fro. The police were thoroughly satisfied and prepared to depart. The glee at my heart was too strong to be restrained. I burned to say if but one word, by way of triumph, and to render doubly sure their assurance of my guiltlessness.",
      "“Gentlemen,” I said at last, as the party ascended the steps, “I delight to have allayed your suspicions. I wish you all health and a little more courtesy. By the bye, gentlemen, this—this is a very well-constructed house,” (in the rabid desire to say something easily, I scarcely knew what I uttered at all),—“I may say an excellently well-constructed house. These walls—are you going, gentlemen?—these walls are solidly put together”; and here, through the mere frenzy of bravado, I rapped heavily with a cane which I held in my hand, upon that very portion of the brickwork behind which stood the corpse of the wife of my bosom.",
      "But may God shield and deliver me from the fangs of the Arch-Fiend! No sooner had the reverberation of my blows sunk into silence, than I was answered by a voice from within the tomb!—by a cry, at first muffled and broken, like the sobbing of a child, and then quickly swelling into one long, loud, and continuous scream, utterly anomalous and inhuman—a howl—a wailing shriek, half of horror and half of triumph, such as might have arisen only out of hell, conjointly from the throats of the dammed in their agony and of the demons that exult in the damnation.",
      "Of my own thoughts it is folly to speak. Swooning, I staggered to the opposite wall. For one instant the party upon the stairs remained motionless, through extremity of terror and awe. In the next a dozen stout arms were toiling at the wall. It fell bodily. The corpse, already greatly decayed and clotted with gore, stood erect before the eyes of the spectators. Upon its head, with red extended mouth and solitary eye of fire, sat the hideous beast whose craft had seduced me into murder, and whose informing voice had consigned me to the hangman. I had walled the monster up within the tomb."
    ]
  },
  'modest-proposal': {
    title: 'A Modest Proposal',
    author: 'Jonathan Swift',
    year: '1729',
    theme: 'Political Satire',
    readTime: '10 min',
    dropCap: 'I',
    pullQuote: "I have been assured by a very knowing American of my acquaintance in London, that a young healthy child well nursed is at a year old a most delicious, nourishing, and wholesome food.",
    content: [
      "It is a melancholy object to those, who walk through this great town, or travel in the country, when they see the streets, the roads and cabin doors crowded with beggars of the female sex, followed by three, four, or six children, all in rags, and importuning every passenger for an alms. These mothers instead of being able to work for their honest livelihood, are forced to employ all their time in strolling to beg sustenance for their helpless infants who, as they grow up, either turn thieves for want of work, or leave their dear native country, to fight for the Pretender in Spain, or sell themselves to the Barbadoes.",
      "I think it is agreed by all parties, that this prodigious number of children in the arms, or on the backs, or at the heels of their mothers, and frequently of their fathers, is in the present deplorable state of the kingdom, a very great additional grievance; and therefore whoever could find out a fair, cheap and easy method of making these children sound and useful members of the commonwealth, would deserve so well of the public, as to have his statue set up for a preserver of the nation.",
      "But my intention is very far from being confined to provide only for the children of professed beggars: it is of a much greater extent, and shall take in the whole number of infants at a certain age, who are born of parents in effect as little able to support them, as those who demand our charity in the streets.",
      "As to my own part, having turned my thoughts for many years, upon this important subject, and maturely weighed the several schemes of our projectors, I have always found them grossly mistaken in their computation. It is true, a child just dropped from its dam, may be supported by her milk, for a solar year, with little other nourishment: at most not above the value of two shillings, which the mother may certainly get, or the value in scraps, by her lawful occupation of begging; and it is exactly at one year old that I propose to provide for them in such a manner, as, instead of being a charge upon their parents, or the parish, or wanting food and raiment for the rest of their lives, they shall, on the contrary, contribute to the feeding, and partly to the clothing of many thousands. There is likewise another great advantage in my scheme, that it will prevent those voluntary abortions, and that horrid practice of women murdering their bastard children, alas! too frequent among us, sacrificing the poor innocent babes, I doubt, more to avoid the expense than the shame, which would move tears and pity in the most savage and inhuman breast.",
      "The number of souls in this kingdom being usually reckoned one million and a half, of these I calculate there may be about two hundred thousand couple whose wives are breeders; from which number I subtract thirty thousand couple, who are able to maintain their own children, (although I apprehend there cannot be so many, under the present distresses of the kingdom) but this being granted, there will remain an hundred and seventy thousand breeders. I again subtract fifty thousand, for those women who miscarry, or whose children die by accident or disease within the year. There only remain an hundred and twenty thousand children of poor parents annually born. The question therefore is, How this number shall be reared, and provided for? which, as I have already said, under the present situation of affairs, is utterly impossible by all the methods hitherto proposed. For we can neither employ them in handicraft or agriculture; we neither build houses, (I mean in the country) nor cultivate land: they can very seldom pick up a livelihood by stealing till they arrive at six years old; except where they are of towardly parts, although I confess they learn the rudiments much earlier; during which time they can however be properly looked upon only as probationers: As I have been informed by a principal gentleman in the county of Cavan, who protested to me, that he never knew above one or two instances under the age of six, even in a part of the kingdom so renowned for the quickest proficiency in that art.",
      "I am assured by our merchants, that a boy or a girl before twelve years old, is no saleable commodity, and even when they come to this age, they will not yield above three pounds, or three pounds and half a crown at most, on the exchange; which cannot turn to account either to the parents or kingdom, the charge of nutriments and rags having been at least four times that value.",
      "I shall now therefore humbly propose my own thoughts, which I hope will not be liable to the least objection.",
      "I have been assured by a very knowing American of my acquaintance in London, that a young healthy child well nursed, is, at a year old, a most delicious nourishing and wholesome food, whether stewed, roasted, baked, or boiled; and I make no doubt that it will equally serve in a fricasie, or a ragoust.",
      "I do therefore humbly offer it to public consideration, that of the hundred and twenty thousand children, already computed, twenty thousand may be reserved for breed, whereof only one fourth part to be males; which is more than we allow to sheep, black cattle, or swine, and my reason is, that these children are seldom the fruits of marriage, a circumstance not much regarded by our savages, therefore, one male will be sufficient to serve four females. That the remaining hundred thousand may, at a year old, be offered in sale to the persons of quality and fortune, through the kingdom, always advising the mother to let them suck plentifully in the last month, so as to render them plump, and fat for a good table. A child will make two dishes at an entertainment for friends, and when the family dines alone, the fore or hind quarter will make a reasonable dish, and seasoned with a little pepper or salt, will be very good boiled on the fourth day, especially in winter.",
      "I have reckoned upon a medium, that a child just born will weigh 12 pounds, and in a solar year, if tolerably nursed, increases to 28 pounds.",
      "I grant this food will be somewhat dear, and therefore very proper for landlords, who, as they have already devoured most of the parents, seem to have the best title to the children.",
      "Infant's flesh will be in season throughout the year, but more plentiful in March, and a little before and after; for we are told by a grave author, an eminent French physician, that fish being a prolific diet, there are more children born in Roman Catholic countries about nine months after Lent, the markets will be more glutted than usual, because the number of Popish infants, is at least three to one in this kingdom, and therefore it will have one other collateral advantage, by lessening the number of Papists among us.",
      "I have already computed the charge of nursing a beggar's child (in which list I reckon all cottagers, laborers, and four-fifths of the farmers) to be about two shillings per annum, rags included; and I believe no gentleman would repine to give ten shillings for the carcass of a good fat child, which, as I have said, will make four dishes of excellent nutritive meat, when he hath only some particular friend, or his own family to dine with him. Thus the squire will learn to be a good landlord, and grow popular among his tenants, the mother will have eight shillings neat profit, and be fit for work till she produces another child.",
      "Those who are more thrifty (as I must confess the times require) may flea the carcass; the skin of which, artificially dressed, will make admirable gloves for ladies, and summer boots for fine gentlemen.",
      "As to our City of Dublin, shambles may be appointed for this purpose, in the most convenient parts of it, and butchers we may be assured will not be wanting; although I rather recommend buying the children alive, and dressing them hot from the knife, as we do roasting pigs.",
      "A very worthy person, a true lover of his country, and whose virtues I highly esteem, was lately pleased, in discoursing on this matter, to offer a refinement upon my scheme. He said, that many gentlemen of this kingdom, having of late destroyed their deer, he conceived that the want of venison might be well supplied by the bodies of young lads and maidens, not exceeding fourteen years of age, nor under twelve; so great a number of both sexes in every country being now ready to starve for want of work and service: And these to be disposed of by their parents if alive, or otherwise by their nearest relations. But with due deference to so excellent a friend, and so deserving a patriot, I cannot be altogether in his sentiments; for as to the males, my American acquaintance assured me from frequent experience, that their flesh was generally tough and lean, like that of our school-boys, by continual exercise, and their taste disagreeable, and to fatten them would not answer the charge. Then as to the females, it would, I think, with humble submission, be a loss to the public, because they soon would become breeders themselves: And besides, it is not improbable that some scrupulous people might be apt to censure such a practice, (although indeed very unjustly) as a little bordering upon cruelty, which, I confess, hath always been with me the strongest objection against any project, how well soever intended.",
      "But in order to justify my friend, he confessed, that this expedient was put into his head by the famous Salmanaazor, a native of the island Formosa, who came from thence to London, above twenty years ago, and in conversation told my friend, that in his country, when any young person happened to be put to death, the executioner sold the carcass to persons of quality, as a prime dainty; and that, in his time, the body of a plump girl of fifteen, who was crucified for an attempt to poison the Emperor, was sold to his imperial majesty's prime minister of state, and other great mandarins of the court in joints from the gibbet, at four hundred crowns. Neither indeed can I deny, that if the same use were made of several plump young girls in this town, who without one single groat to their fortunes, cannot stir abroad without a chair, and appear at a playhouse and assemblies in foreign fineries which they never will pay for; the kingdom would not be the worse.",
      "Some persons of a desponding spirit are in great concern about that vast number of poor people, who are aged, diseased, or maimed; and I have been desired to employ my thoughts what course may be taken, to ease the nation of so grievous an encumbrance. But I am not in the least pain upon that matter, because it is very well known, that they are every day dying, and rotting, by cold and famine, and filth, and vermin, as fast as can be reasonably expected. And as to the young laborers, they are now in almost as hopeful a condition. They cannot get work, and consequently pine away from want of nourishment, to a degree, that if at any time they are accidentally hired to common labor, they have not strength to perform it, and thus the country and themselves are happily delivered from the evils to come.",
      "I have too long digressed, and therefore shall return to my subject. I think the advantages by the proposal which I have made are obvious and many, as well as of the highest importance.",
      "For first, as I have already observed, it would greatly lessen the number of Papists, with whom we are yearly over-run, being the principal breeders of the nation, as well as our most dangerous enemies, and who stay at home on purpose with a design to deliver the kingdom to the Pretender, hoping to take their advantage by the absence of so many good Protestants, who have chosen rather to leave their country, than stay at home and pay tithes against their conscience to an episcopal curate.",
      "Secondly, The poorer tenants will have something valuable of their own, which by law may be made liable to a distress, and help to pay their landlord's rent, their corn and cattle being already seized, and money a thing unknown.",
      "Thirdly, Whereas the maintenance of an hundred thousand children, from two years old, and upwards, cannot be computed at less than ten shillings a piece per annum, the nation's stock will be thereby increased fifty thousand pounds per annum, besides the profit of a new dish, introduced to the tables of all gentlemen of fortune in the kingdom, who have any refinement in taste. And the money will circulate among our selves, the goods being entirely of our own growth and manufacture.",
      "Fourthly, The constant breeders, besides the gain of eight shillings sterling per annum by the sale of their children, will be rid of the charge of maintaining them after the first year.",
      "Fifthly, This food would likewise bring great custom to taverns, where the vintners will certainly be so prudent as to procure the best receipts for dressing it to perfection; and consequently have their houses frequented by all the fine gentlemen, who justly value themselves upon their knowledge in good eating; and a skilful cook, who understands how to oblige his guests, will contrive to make it as expensive as they please.",
      "Sixthly, This would be a great inducement to marriage, which all wise nations have either encouraged by rewards, or enforced by laws and penalties. It would increase the care and tenderness of mothers towards their children, when they were sure of a settlement for life to the poor babes, provided in some sort by the public, to their annual profit instead of expense. We should soon see an honest emulation among the married women, which of them could bring the fattest child to the market. Men would become as fond of their wives, during the time of their pregnancy, as they are now of their mares in foal, their cows in calf, or sow when they are ready to farrow; nor offer to beat or kick them (as is too frequent a practice) for fear of a miscarriage.",
      "Many other advantages might be enumerated. For instance, the addition of some thousand carcasses in our exportation of barreled beef: the propagation of swine's flesh, and improvement in the art of making good bacon, so much wanted among us by the great destruction of pigs, too frequent at our tables; which are no way comparable in taste or magnificence to a well grown, fat yearly child, which roasted whole will make a considerable figure at a Lord Mayor's feast, or any other public entertainment. But this, and many others, I omit, being studious of brevity.",
      "Supposing that one thousand families in this city, would be constant customers for infants flesh, besides others who might have it at merry meetings, particularly at weddings and christenings, I compute that Dublin would take off annually about twenty thousand carcasses; and the rest of the kingdom (where probably they will be sold somewhat cheaper) the remaining eighty thousand.",
      "I can think of no one objection, that will possibly be raised against this proposal, unless it should be urged, that the number of people will be thereby much lessened in the kingdom. This I freely own, and 'twas indeed one principal design in offering it to the world. I desire the reader will observe, that I calculate my remedy for this one individual Kingdom of Ireland, and for no other that ever was, is, or, I think, ever can be upon Earth. Therefore let no man talk to me of other expedients: Of taxing our absentees at five shillings a pound: Of using neither clothes, nor household furniture, except what is of our own growth and manufacture: Of utterly rejecting the materials and instruments that promote foreign luxury: Of curing the expensiveness of pride, vanity, idleness, and gaming in our women: Of introducing a vein of parsimony, prudence and temperance: Of learning to love our country, wherein we differ even from Laplanders, and the inhabitants of Topinamboo: Of quitting our animosities and factions, nor acting any longer like the Jews, who were murdering one another at the very moment their city was taken: Of being a little cautious not to sell our country and consciences for nothing: Of teaching landlords to have at least one degree of mercy towards their tenants. Lastly, of putting a spirit of honesty, industry, and skill into our shopkeepers, who, if a resolution could now be taken to buy only our native goods, would immediately unite to cheat and exact upon us in the price, the measure, and the goodness, nor could ever yet be brought to make one fair proposal of just dealing, though often and earnestly invited to it.",
      "Therefore I repeat, let no man talk to me of these and the like expedients, 'till he hath at least some glimpse of hope, that there will ever be some hearty and sincere attempt to put them into practice.",
      "But, as to my self, having been wearied out for many years with offering vain, idle, visionary thoughts, and at length utterly despairing of success, I fortunately fell upon this proposal, which, as it is wholly new, so it hath something solid and real, of no expense and little trouble, full in our own power, and whereby we can incur no danger in disobliging England. For this kind of commodity will not bear exportation, and flesh being of too tender a consistence, to admit a long continuance in salt, although perhaps I could name a country, which would be glad to eat up our whole nation without it.",
      "After all, I am not so violently bent upon my own opinion, as to reject any offer, proposed by wise men, which shall be found equally innocent, cheap, easy, and effectual. But before something of that kind shall be advanced in contradiction to my scheme, and offering a better, I desire the author or authors will be pleased maturely to consider two points. First, As things now stand, how they will be able to find food and raiment for a hundred thousand useless mouths and backs. And secondly, There being a round million of creatures in humane figure throughout this kingdom, whose whole subsistence put into a common stock, would leave them in debt two million of pounds sterling, adding those who are beggars by profession, to the bulk of farmers, cottagers and laborers, with their wives and children, who are beggars in effect; I desire those politicians who dislike my overture, and may perhaps be so bold to attempt an answer, that they will first ask the parents of these mortals, whether they would not at this day think it a great happiness to have been sold for food at a year old, in the manner I prescribe, and thereby have avoided such a perpetual scene of misfortunes, as they have since gone through, by the oppression of landlords, the impossibility of paying rent without money or trade, the want of common sustenance, with neither house nor clothes to cover them from the inclemencies of the weather, and the most inevitable prospect of entailing the like, or greater miseries, upon their breed for ever.",
      "I profess, in the sincerity of my heart, that I have not the least personal interest in endeavoring to promote this necessary work, having no other motive than the public good of my country, by advancing our trade, providing for infants, relieving the poor, and giving some pleasure to the rich. I have no children, by which I can propose to get a single penny; the youngest being nine years old, and my wife past childbearing."
    ]
  }
}

export default function StoryPage({ params }: { params: { id: string } }) {
  const story = storyData[params.id as keyof typeof storyData]

  if (!story) {
    notFound()
  }

  return (
    <article className="min-h-screen bg-paper">
      {/* Sticky Navigation Header */}
      <nav className="fixed top-0 left-0 w-full px-6 py-4 flex justify-between items-center z-50 bg-paper/80 backdrop-blur-md border-b border-moss-200">
        <Link
          href="/"
          className="flex items-center space-x-2 text-moss-800 hover:text-moss-600 transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
          <span className="font-sans text-xs tracking-widest uppercase font-medium">Back to Collection</span>
        </Link>

        <div className="flex items-center space-x-4 text-moss-800">
          <BookOpen className="w-5 h-5 opacity-50" />
        </div>
      </nav>

      {/* Hero Header */}
      <header className="pt-40 pb-20 px-6 max-w-3xl mx-auto text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <div className="inline-block px-3 py-1 mb-6 border border-moss-300 rounded-full">
            <span className="font-sans text-xs tracking-widest text-moss-600 uppercase">{story.theme}</span>
          </div>
          <h1 className="font-serif text-5xl md:text-7xl text-ink mb-6 leading-tight">
            {story.title}
          </h1>
          <div className="flex items-center justify-center space-x-4 font-sans text-sm text-moss-700 tracking-wide">
            <span className="font-bold">{story.author}</span>
            <span>•</span>
            <span>{story.year}</span>
            <span>•</span>
            <div className="flex items-center">
              <Clock className="w-4 h-4 mr-1 opacity-70" />
              {story.readTime}
            </div>
          </div>
        </motion.div>
      </header>

      {/* Main Content */}
      <main className="max-w-2xl mx-auto px-6 pb-32">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4, duration: 1 }}
          className="prose prose-lg prose-stone prose-headings:font-serif prose-p:font-serif prose-p:text-ink/80 prose-p:leading-loose"
        >
          {story.content.map((paragraph, index) => (
            <>
              <p key={index} className={index === 0 ? "first-letter:float-left first-letter:text-7xl first-letter:pr-4 first-letter:font-serif first-letter:text-moss-900 first-line:uppercase first-line:tracking-widest" : ""}>
                {index === 0 && story.dropCap}{paragraph}
              </p>
              {index === 2 && story.pullQuote && (
                <div className="my-12 relative">
                  <div className="absolute top-0 left-0 -ml-4 w-1 h-full bg-moss-300" />
                  <blockquote className="pl-8 font-serif text-2xl md:text-3xl italic text-moss-800 leading-relaxed">
                    &ldquo;{story.pullQuote}&rdquo;
                  </blockquote>
                </div>
              )}
            </>
          ))}
        </motion.div>

        {/* Footer Navigation */}
        <div className="mt-20 pt-10 border-t border-moss-200 flex justify-between">
          <Link href="/" className="font-serif text-moss-800 italic hover:underline">
            ← Return to Index
          </Link>
        </div>
      </main>
    </article>
  )
}
